"""
Type:
101 - Tab Navigation
201 - Tab Navigation
301 - Tab Navigation
401 - Tab Navigation
501 - Tab Navigation
601 - Detail Video
701 - Actress
801 - Search
Placement: apps | banner | swipper, toast, splash
"""
import requests

ADS = [
    {
        "name": "免费看片",
        "sequence": 0,
        "image_url": "https://img04.sogoucdn.com/app/a/200692/100_100_feedback_60daceb5a16a4099abf92f73f7c1d4c8.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'horizontal',
        "status": 1,
        "is_archived": 0,
        "created_by": "system",
        "updated_by": "system",
    },
    {
        "name": "妈咪直播",
        "sequence": 1,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_f6fbf35f9a114a6a9ee22b088d223e27.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'horizontal',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "嫦娥直播",
        "sequence": 2,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_102_feedback_4fe56d80e8434ed7826bd89b326bb2ac.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'horizontal',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "伊人视频",
        "sequence": 3,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_0fffdebcd15c4757af792755afefac24.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'horizontal',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "身材诱惑",
        "sequence": 4,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_100_feedback_79ab9b25e6b04b9d8a6862b7b9a3d5eb.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'horizontal',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "西施直播",
        "sequence": 5,
        "image_url": "https://img04.sogoucdn.com/app/a/200692/90_90_feedback_f43cfd637158416fb893d27ebd4083f6.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'horizontal',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "我和表妹",
        "sequence": 6,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_ec00c71b422a4b97a7e9dfb665d3102e.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "大发彩票",
        "sequence": 7,
        "image_url": "https://pic.imgdb.cn/item/640f0bd2f144a01007baddd2.jpg",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "91视频",
        "sequence": 8,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_100_feedback_9b49eeedd4d64437805fc1585f4e0704.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "好色先生",
        "sequence": 9,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_c0679f26f37142189a97ae683776d6b4.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "爵色免费版",
        "sequence": 0,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_101_feedback_828e8688d2eb4d918bf6ae83270f1aec.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "小黄鸭",
        "sequence": 1,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_101_feedback_4493f766a3b94a3483e767b9841c8a64.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "精品免费",
        "sequence": 2,
        "image_url": "https://img04.sogoucdn.com/app/a/200692/100_100_feedback_6bf210b934c34b9a828764c07f329ac0.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "免费A片",
        "sequence": 3,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_327edb278cb944a9adf3b60c7a150cf8.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "青青草",
        "sequence": 4,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_e0e9bb10a5e54edaa034fbb6844305cb.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "免费黄瓜",
        "sequence": 5,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_ec00c71b422a4b97a7e9dfb665d3102e.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "精品免费视频",
        "sequence": 6,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_f6fbf35f9a114a6a9ee22b088d223e27.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "麻豆传媒免费",
        "sequence": 7,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_100_feedback_ba07e415827044f491a9be2ada0a686b.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "羞羞视频",
        "sequence": 8,
        "image_url": "https://img01.sogoucdn.com/app/a/200692/80_80_feedback_714d45709b914f309dd35e40fd639ad7.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "粉色AV",
        "sequence": 9,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_100_feedback_6fb8952f60be4dc38f4fcd834890bed2.gif",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "成人漫画破解",
        "sequence": 0,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_101_feedback_828e8688d2eb4d918bf6ae83270f1aec.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "好莱污破解",
        "sequence": 1,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/256_256_feedback_5ed5638cc7d6466886c6f27bc532f57b.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "糖心破解",
        "sequence": 2,
        "image_url": "https://img04.sogoucdn.com/app/a/200692/90_90_feedback_f43cfd637158416fb893d27ebd4083f6.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "小优破解",
        "sequence": 3,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_101_feedback_4493f766a3b94a3483e767b9841c8a64.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "骚狐视频",
        "sequence": 4,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_102_feedback_4fe56d80e8434ed7826bd89b326bb2ac.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "妈咪直播",
        "sequence": 5,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_f6fbf35f9a114a6a9ee22b088d223e27.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "義父的爱",
        "sequence": 6,
        "image_url": "https://img03.sogoucdn.com/app/a/200692/100_100_feedback_e0e9bb10a5e54edaa034fbb6844305cb.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "淫穴学姐",
        "sequence": 7,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_100_feedback_c3aaf8de6c764c80a0bee69c266ced2f.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "巨乳学妹",
        "sequence": 8,
        "image_url": "https://img01.sogoucdn.com/app/a/200692/100_100_feedback_699f58903efb40dc821885f92d6476f7.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "JK小妹妹",
        "sequence": 9,
        "image_url": "https://img02.sogoucdn.com/app/a/200692/100_100_feedback_7ab9faa5864e4796b59a6dd2dc711335.gif",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": 'apps',
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 1.1",
        "sequence": 0,
        "image_url": "https://hw-cdn2.adtng.com/a7/creatives/1/49/811560/987467/987467_banner.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 1.2",
        "sequence": 1,
        "image_url": "https://hw-cdn2.adtng.com/a7/creatives/1/49/815548/1054219/1054219_banner.gif",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner- 2.1",
        "sequence": 0,
        "image_url": "https://webcamstartup.com/wp-content/uploads/2017/11/xhamster.jpg",
        "link_url": "https://www.google.com/",
        "type": 501,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner- 2.2",
        "sequence": 1,
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN8iWBtUyBWhAa0x0cv230ZDNrOuV7OSpGZQ&usqp=CAU",
        "link_url": "https://www.google.com/",
        "type": 501,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner- 2.3",
        "sequence": 2,
        "image_url": "https://1000logos.net/wp-content/uploads/2017/12/Emblem-Pornhub.jpg",
        "link_url": "https://www.google.com/",
        "type": 501,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 3",
        "sequence": 0,
        "image_url": "https://hw-cdn2.adtng.com/a7/creatives/1/49/811560/986874/986874_banner.gif",
        "link_url": "https://www.google.com/",
        "type": 601,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 3.1",
        "sequence": 0,
        "image_url": "https://cdn6.f-cdn.com/contestentries/1784089/43380798/5ef69bb4e0ff9_thumb900.jpg",
        "link_url": "https://www.google.com/",
        "type": 601,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 3.2",
        "sequence": 0,
        "image_url": "https://cdn5.f-cdn.com/contestentries/1784089/43380798/5ef69bdcebfe1_thumb900.jpg",
        "link_url": "https://www.google.com/",
        "type": 601,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 3.3",
        "sequence": 0,
        "image_url":"https://ht-cdn2.trafficjunky.net/a7/creatives/1/49/813194/1009801/1009801_banner.gif",
        "link_url": "https://www.google.com/",
        "type": 601,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 4",
        "sequence": 0,
        "image_url": "https://cdn.x1cdn.com/fa/18exgfs/rwd/join/banner-sm.jpg",
        "link_url": "https://www.google.com/",
        "type": 701,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "banner - 5",
        "sequence": 0,
        "image_url": "https://cdn.goasrv.com/data/creatives/1164/26365.webp",
        "link_url": "https://www.google.com/",
        "type": 801,
        "placement": "banner",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 1.1",
        "sequence": 0,
        "image_url": "https://images.weknowporn.com/wp-content/uploads/2023/03/wkp_header_2023.jpg",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 1.2",
        "sequence": 1,
        "image_url": "https://1000logos.net/wp-content/uploads/2017/12/Pornhub-Logo-2009.png",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 1.3",
        "sequence": 2,
        "image_url": "https://media.zenfs.com/en/consequence_of_sound_458/c294809e4cb18ff6c2c35861aa041b01",
        "link_url": "https://www.google.com/",
        "type": 101,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 2.1",
        "sequence": 0,
        "image_url": ("https://intlsexguide.com/wp-content/uploads/2022/08/name-that-porn-ad-best-brazzers-porn-ads-min.png"),
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 2.2",
        "sequence": 1,
        "image_url":"https://cdn3.f-cdn.com/contestentries/981449/21541178/58d54bb1b0109_thumb900.jpg",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 2.3",
        "sequence": 2,
        "image_url": "https://techcrunch.com/wp-content/uploads/2020/12/pornhub-logo.jpg?w=730&crop=1/",
        "link_url": "https://www.google.com/",
        "type": 201,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 3.1",
        "sequence": 0,
        "image_url":"https://redwap-xxx.com/wp-content/uploads/2021/08/porn-hub-video-com.jpg",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 3.2",
        "sequence": 1,
        "image_url": "https://i.ebayimg.com/images/g/uUoAAOSwxwRattAX/s-l500.jpg",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "swiper - 3.3",
        "sequence": 2,
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaOSP9ewuBaC5bYq3rZp5qguR4Sk6J2cul1g&usqp=CAU",
        "link_url": "https://www.google.com/",
        "type": 301,
        "placement": "swiper",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "splash - 1",
        "sequence": 0,
        "image_url": "https://550wjmnwiqwo.com/shg/bg-01.jpg",
        "link_url": "https://www.google.com/",
        "type": False,
        "placement": "splash",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "toast - 1",
        "sequence": 0,
        "image_url": "https://550wjmnwiqwo.com/shg/bg-02.jpg",
        "link_url": "https://www.google.com/",
        "type": False,
        "placement": "toast",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "toast - 2",
        "sequence": 1,
        "image_url": "https://550wjmnwiqwo.com/shg/bg-03.jpg",
        "link_url": "https://www.google.com/",
        "type": False,
        "placement": "toast",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    },
    {
        "name": "toast - 3",
        "sequence": 2,
        "image_url": "https://550wjmnwiqwo.com/shg/bg-04.jpg",
        "link_url": "https://www.google.com/",
        "type": False,
        "placement": "toast",
        "view_type": 'list',
        "status": 1,
        'is_archived': 0,
    }
]

list_link= []
placementss = []
image ,placement= '',''
for data in ADS:
    for k,v in data.items():
        if k == 'image_url':
            # image = v
            list_link.append(v)
        elif k =='placement':
            placementss.append(v)
i = 0
for data in list_link:
    response = requests.get(data, stream=True)
    with open(f'photo/{placementss[i]} - {i}.jpg', 'wb') as handle:
        if not response.ok:
            print(response)

        for block in response.iter_content(1024):
            if not block:
                break

            handle.write(block)
    i+=1